### ISSUE TITLE
hung up while downloading

### ISSUE THREAD

**Issue by tinycrops** [adriens/ollama-models#3]
![image](https://github.com/adriens/ollama-models/assets/13264408/fcc869a9-93a7-4788-aa46-b6b9763745b7)

**Comment by adriens** [comment]
So did you manage to get some fun ?

**Comment by tinycrops** [comment]
![Screenshot 2024-01-21 211905](https://github.com/adriens/ollama-models/assets/13264408/64785c08-31a7-4407-932c-56b29d133fce)

**Comment by tinycrops** [comment]
it works great. thank you. I'm a big fan of your work.
![Screenshot 2024-01-21 232813](https://github.com/adriens/ollama-models/assets/13264408/4bdda6ca-e890-4789-b17e-a0c1d4a01b4f)

**Comment by tinycrops** [comment]
yeah we're poppin' off now

**Comment by adriens** [comment]
Cf the following answer:
- https://github.com/adriens/ollama-models/issues/3#issuecomment-1903194983

I really wonder what you asked it: its really brutal and made le LOL😭😭😭😭😭😭😭😭 _"Fat ass and arthritis"_ : it's just awesome :star_struck:

**Comment by adriens** [comment]
> . I'm a big fan of your work.

Thanks a lot for the kind words :pray: :cat:

**Comment by adriens** [comment]
btw, good catch to have used his coding skills as [`dolphin-mistral`](https://ollama.ai/library?q=dolphin-mistral)  _"excels at coding tasks."_ : 

![image](https://github.com/adriens/ollama-models/assets/5235127/bcb131e2-8f81-4d09-b9d7-508f2aee5e28)
